
soul:
  http:
    adminUrl: http://192.168.1.216:9095
    contextPath: /soul
    appName: soul
server:
  tomcat:
    max-threads: 800
    accept-count: 1000

spring:
  cloud:
    sentinel:
      transport:
        port: 18719
        dashboard: 192.168.1.197:18091