server:
  port: 8904

spring:
  application:
    name: eurka-server
  security:
    user:
      name: admin
      password: 123456
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@192.168.1.216:${server.port}/eureka/